version: "2"
services:
  web:
    build: ./frontend-toktok-docker
    ports:
      - 4200:4200
  backend:
    build: ./back-toktok-docker
    container_name: backend
    command: npm run dev
    ports:
      - "3000:3000"
  mongo:
    image: mongo
    ports:
      - 27017:27017

